/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.BookingController;
import Model.BookingT;
import Model.GuideA;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author shita
 */
public class Booking extends javax.swing.JFrame {
    private GuideA guide;
    private BookingT book;
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }
    
    public Booking(GuideA guide){
        initComponents();
        this.guide = guide;
        System.out.println("Guide ID passed to Booking: " + guide.getGuideId());
        
       System.out.println(guide.getFullName());
        
        
    }
    
    public Booking(BookingT book){
        initComponents();
        this.book = book;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bFirstName = new javax.swing.JTextField();
        bMiddleName = new javax.swing.JTextField();
        bLastName = new javax.swing.JTextField();
        bNumber = new javax.swing.JTextField();
        bEmail = new javax.swing.JTextField();
        bNumberOfPeople = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bAge = new javax.swing.JTextField();
        bCountry = new javax.swing.JTextField();
        bNationality = new javax.swing.JTextField();
        bAddress = new javax.swing.JTextField();
        bZipCode = new javax.swing.JTextField();
        bBookNow = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        bStartDate = new com.toedter.calendar.JDateChooser();
        bPayment = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        bEndDate = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(126, 171, 190));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DULUWA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 47, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Frist Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 171, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Middle Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 229, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 288, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 345, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 404, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Start Date:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 79, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Number of people:");
        jLabel8.setPreferredSize(new java.awt.Dimension(116, 34));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        bFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 162, 210, 35));

        bMiddleName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 220, 210, 35));

        bLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 279, 210, 35));

        bNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNumberActionPerformed(evt);
            }
        });
        jPanel2.add(bNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 335, 210, 35));

        bEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 395, 210, 35));

        bNumberOfPeople.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bNumberOfPeople, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 210, 35));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Age:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 175, 37, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Country:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 229, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nationality:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 286, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Address:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 345, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Zip code:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 405, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Payment:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 461, -1, -1));

        bAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgeActionPerformed(evt);
            }
        });
        jPanel2.add(bAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 165, 206, 35));

        bCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 220, 206, 35));

        bNationality.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 277, 206, 35));

        bAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 206, 35));

        bZipCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(bZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 395, 206, 35));

        bBookNow.setBackground(new java.awt.Color(40, 83, 107));
        bBookNow.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bBookNow.setForeground(new java.awt.Color(255, 255, 255));
        bBookNow.setText("Book Now");
        bBookNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBookNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBookNowActionPerformed(evt);
            }
        });
        jPanel2.add(bBookNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 638, -1, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/logo1.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 25, 115, -1));

        bStartDate.setPreferredSize(new java.awt.Dimension(88, 34));
        jPanel2.add(bStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 144, -1));

        bPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "esewa", "cash" }));
        bPayment.setPreferredSize(new java.awt.Dimension(72, 34));
        jPanel2.add(bPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 453, 206, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("How long would you like to book the guide for?");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 505, -1, -1));

        bEndDate.setPreferredSize(new java.awt.Dimension(88, 34));
        jPanel2.add(bEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 149, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("End Date:");
        jLabel17.setPreferredSize(new java.awt.Dimension(44, 34));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 64, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAgeActionPerformed

    private void bNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNumberActionPerformed

    private void bBookNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBookNowActionPerformed
        // TODO add your handling code here:
        
        try {
            Date selectedDate = bStartDate.getDate();
            Date endDate = bEndDate.getDate();

            if (selectedDate == null || endDate == null) {
                JOptionPane.showMessageDialog(this, "Please select both Start Date and End Date.");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String startDateText = sdf.format(selectedDate);
            String endDateText = sdf.format(endDate);

            String firstNameText = bFirstName.getText().trim();
            String middleNameText = bMiddleName.getText().trim();
            String lastNameText = bLastName.getText().trim();
            String phoneNumberText = bNumber.getText().trim();
            String emailText = bEmail.getText().trim();
            String peopleText = bNumberOfPeople.getText().trim();
            String ageText = bAge.getText().trim();
            String countryText = bCountry.getText().trim();
            String nationalityText = bNationality.getText().trim();
            String addressText = bAddress.getText().trim();
            String zipCodeText = bZipCode.getText().trim();
            String paymentText = (String) bPayment.getSelectedItem();

            // ✅ Optional: simple field presence check before calling bookingAll()
            if (firstNameText.isEmpty() || lastNameText.isEmpty() || phoneNumberText.isEmpty() || emailText.isEmpty() ||
                peopleText.isEmpty() || ageText.isEmpty() || addressText.isEmpty() || zipCodeText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all required fields.");
                return;
            }

            // ✅ Call booking method
            this.book = BookingController.bookingAll(
                firstNameText, middleNameText, lastNameText, phoneNumberText, emailText,
                startDateText, peopleText, ageText, countryText, nationalityText,
                addressText, zipCodeText, paymentText, endDateText, guide, Booking.this
            );

            if (this.book != null) {
                BookingReceipt receipt = new BookingReceipt(this.book);
                receipt.setVisible(true);
                receipt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } else {
                JOptionPane.showMessageDialog(this, "Booking failed. Cannot show receipt.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
        }

    }//GEN-LAST:event_bBookNowActionPerformed
    
//    public void generateReceipt(){
//        Date selectedDate = bStartDate.getDate(); 
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
//        Date endDate = bEndDate.getDate(); 
//        SimpleDateFormat end = new SimpleDateFormat("yyyy-MM-dd"); 
//        String firstNameText = bFirstName.getText();
//        String middleNameText = bMiddleName.getText();
//        String lastNameText = bLastName.getText();
//        String phoneNumberText = bNumber.getText();
//        String emailText = bEmail.getText();
//        String startDateText = sdf.format(selectedDate);
//        String peopleText = bNumberOfPeople.getText();
//        String ageText = bAge.getText();
//        String countryText = bCountry.getText();
//        String nationalityText = bNationality.getText();
//        String addressText = bAddress.getText();
//        String zipCodeText = bZipCode.getText();
//        String paymentText =(String) bPayment.getSelectedItem();
//        String endDateText = end.format(endDate);
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bAddress;
    private javax.swing.JTextField bAge;
    private javax.swing.JButton bBookNow;
    private javax.swing.JTextField bCountry;
    private javax.swing.JTextField bEmail;
    private com.toedter.calendar.JDateChooser bEndDate;
    private javax.swing.JTextField bFirstName;
    private javax.swing.JTextField bLastName;
    private javax.swing.JTextField bMiddleName;
    private javax.swing.JTextField bNationality;
    private javax.swing.JTextField bNumber;
    private javax.swing.JTextField bNumberOfPeople;
    private javax.swing.JComboBox<String> bPayment;
    private com.toedter.calendar.JDateChooser bStartDate;
    private javax.swing.JTextField bZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
