/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProfileController;
import Controller.UserController;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author acer
 */
public class userProfileEdit extends javax.swing.JFrame {
    private int userId;
    UserController controller;
    private Dashboard dashboard;
    /**
     * Creates new form userProfileEdit
     */
    public userProfileEdit() {
        initComponents();
        pGender.setModel(new DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

    }
    
    public userProfileEdit(int userId, Dashboard dashboard) {
        this.userId = userId;
        initComponents();
        this.dashboard = dashboard;
        controller = new UserController(userId, this);
        controller.loadProfile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pBio = new javax.swing.JTextArea();
        pFirstName = new javax.swing.JTextField();
        pMiddleName = new javax.swing.JTextField();
        pLastName = new javax.swing.JTextField();
        pAge = new javax.swing.JTextField();
        pNationality = new javax.swing.JTextField();
        pCountry = new javax.swing.JTextField();
        pUpdate = new javax.swing.JButton();
        pGender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("First Name:");
        jLabel2.setPreferredSize(new java.awt.Dimension(68, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Middle Name:");
        jLabel3.setPreferredSize(new java.awt.Dimension(86, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Last Name:");
        jLabel4.setPreferredSize(new java.awt.Dimension(72, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Age:");
        jLabel5.setPreferredSize(new java.awt.Dimension(29, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nationality:");
        jLabel6.setPreferredSize(new java.awt.Dimension(70, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Country:");
        jLabel7.setPreferredSize(new java.awt.Dimension(54, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Gender:");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bio:");
        jLabel9.setPreferredSize(new java.awt.Dimension(24, 34));

        pBio.setColumns(20);
        pBio.setRows(5);
        jScrollPane1.setViewportView(pBio);

        pFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pFirstName.setPreferredSize(new java.awt.Dimension(64, 34));
        pFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pFirstNameActionPerformed(evt);
            }
        });

        pMiddleName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pMiddleName.setPreferredSize(new java.awt.Dimension(64, 34));
        pMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMiddleNameActionPerformed(evt);
            }
        });

        pLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pLastName.setPreferredSize(new java.awt.Dimension(64, 34));
        pLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pLastNameActionPerformed(evt);
            }
        });

        pAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pAge.setPreferredSize(new java.awt.Dimension(64, 34));

        pNationality.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pNationality.setPreferredSize(new java.awt.Dimension(64, 34));

        pCountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pCountry.setPreferredSize(new java.awt.Dimension(64, 34));
        pCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCountryActionPerformed(evt);
            }
        });

        pUpdate.setBackground(new java.awt.Color(40, 83, 107));
        pUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pUpdate.setForeground(new java.awt.Color(255, 255, 255));
        pUpdate.setText("update");
        pUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pUpdate.setPreferredSize(new java.awt.Dimension(80, 34));
        pUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pUpdateActionPerformed(evt);
            }
        });

        pGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female" }));
        pGender.setPreferredSize(new java.awt.Dimension(72, 34));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(pMiddleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pNationality, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pGender, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(pUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pMiddleNameActionPerformed

    private void pLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pLastNameActionPerformed

    private void pCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCountryActionPerformed

    private void pUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pUpdateActionPerformed
        // TODO add your handling code here:
//        String firstName = pFirstName.getText();
//        String middleName = pMiddleName.getText();
//        String lastName = pLastName.getText();
//        String ageText = pAge.getText();
//        String nationality = pNationality.getText();
//        String country= pCountry.getText();
//        String gender =(String) pGender.getSelectedItem();
//        String bio= pBio.getText();
//        
//        
//        this.userId = UserController.updateProfile(
//            firstName, middleName, lastName, ageText, nationality, country,
//            gender,bio, userProfileEdit.this
//        );
//        controller = new UserController(userId, this);
System.out.println("Update button clicked");

        controller.updateProfile();
    }//GEN-LAST:event_pUpdateActionPerformed

    private void pFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pFirstNameActionPerformed
    
    // First Name
    public String getFirstName() {
        return pFirstName.getText().trim();
    }
    public void setFirstName(String name) {
        pFirstName.setText(name);
    }

    // Middle Name
    public String getMiddleName() {
        return pMiddleName.getText().trim();
    }
    public void setMiddleName(String name) {
        pMiddleName.setText(name);
    }

    // Last Name
    public String getLastName() {
        return pLastName.getText().trim();
    }
    public void setLastName(String name) {
        pLastName.setText(name);
    }

    // Age
    public String getAge() {
        return pAge.getText().trim();
    }
    public void setAge(String age) {
        pAge.setText(age);
    }

    // Nationality
    public String getNationality() {
        return pNationality.getText().trim();
    }
    public void setNationality(String nationality) {
        pNationality.setText(nationality);
    }

    // Country
    public String getCountry() {
        return pCountry.getText().trim();
    }
    public void setCountry(String country) {
        pCountry.setText(country);
    }

    // Gender
    public String getGender() {
        return (String) pGender.getSelectedItem();
    }
    public void setGender(String gender) {
        pGender.setSelectedItem(gender);
    }

    // Bio
    public String getBio() {
        return pBio.getText().trim();
    }
    public void setBio(String bio) {
        pBio.setText(bio);
    }
    
    public Dashboard getDashboard() {
        return dashboard;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pAge;
    private javax.swing.JTextArea pBio;
    private javax.swing.JTextField pCountry;
    private javax.swing.JTextField pFirstName;
    private javax.swing.JComboBox<String> pGender;
    private javax.swing.JTextField pLastName;
    private javax.swing.JTextField pMiddleName;
    private javax.swing.JTextField pNationality;
    private javax.swing.JButton pUpdate;
    // End of variables declaration//GEN-END:variables
}
